export type IdTemplateSide = "front" | "back";

export type IdTemplateFieldType = "staticText" | "text" | "image" | "qr" | "shape";

export type IdTemplateTextStyle = {
  fontSize?: number;
  fontWeight?: number;
  color?: string;
  align?: "left" | "center" | "right";
  lineHeight?: number;
  letterSpacing?: string;
  textTransform?: "none" | "uppercase" | "lowercase" | "capitalize";
  fontStyle?: "normal" | "italic";
};

export type IdTemplateField = {
  id: string;
  type: IdTemplateFieldType;
  sourceKey?: string;
  value?: string;
  xPercent: number;
  yPercent: number;
  widthPercent: number;
  heightPercent: number;
  zIndex?: number;
  fit?: "cover" | "contain";
  radius?: string;
  visible?: boolean;
  style?: IdTemplateTextStyle & {
    background?: string;
    border?: string;
    opacity?: number;
  };
};

export type IdTemplate = {
  version: number;
  canvas: {
    width: number;
    height: number;
  };
  sides: Record<IdTemplateSide, { fields: IdTemplateField[] }>;
};

export const DEFAULT_ID_TEMPLATE: IdTemplate = {
  version: 1,
  canvas: {
    width: 856,
    height: 539.8,
  },
  sides: {
    front: {
      fields: [
        {
          id: "front-background",
          type: "shape",
          xPercent: 0,
          yPercent: 0,
          widthPercent: 100,
          heightPercent: 100,
          zIndex: 0,
          style: { background: "#d9d9d9" },
        },
        {
          id: "front-header",
          type: "shape",
          xPercent: 0,
          yPercent: 0,
          widthPercent: 100,
          heightPercent: 19,
          zIndex: 1,
          style: { background: "#071b3d" },
        },
        {
          id: "provincial-seal",
          type: "image",
          sourceKey: "provincialSealUrl",
          xPercent: 3,
          yPercent: 3,
          widthPercent: 9,
          heightPercent: 13,
          zIndex: 2,
          fit: "contain",
        },
        {
          id: "province-name",
          type: "text",
          sourceKey: "province",
          xPercent: 18,
          yPercent: 5,
          widthPercent: 64,
          heightPercent: 6,
          zIndex: 2,
          style: {
            color: "#ffffff",
            fontSize: 18,
            fontWeight: 900,
            align: "center",
            letterSpacing: "0.22em",
            textTransform: "uppercase",
          },
        },
        {
          id: "federation-label",
          type: "staticText",
          value: "Sangguniang Kabataan Provincial Federation",
          xPercent: 22,
          yPercent: 12,
          widthPercent: 56,
          heightPercent: 4,
          zIndex: 2,
          style: {
            color: "#eef4ff",
            fontSize: 8,
            fontWeight: 700,
            align: "center",
            letterSpacing: "0.1em",
            textTransform: "uppercase",
          },
        },
        {
          id: "sk-logo",
          type: "image",
          sourceKey: "skfedLogoUrl",
          xPercent: 87,
          yPercent: 3,
          widthPercent: 10,
          heightPercent: 13,
          zIndex: 2,
          fit: "contain",
        },
        {
          id: "title-band",
          type: "shape",
          xPercent: 0,
          yPercent: 25,
          widthPercent: 100,
          heightPercent: 1.1,
          zIndex: 1,
          style: { background: "#8c0909" },
        },
        {
          id: "card-title",
          type: "staticText",
          value: "Identification Card",
          xPercent: 28,
          yPercent: 21,
          widthPercent: 44,
          heightPercent: 5,
          zIndex: 2,
          style: {
            color: "#111827",
            fontSize: 15,
            fontWeight: 900,
            align: "center",
            letterSpacing: "0.22em",
            textTransform: "uppercase",
          },
        },
        {
          id: "official-photo",
          type: "image",
          sourceKey: "photoUrl",
          xPercent: 5,
          yPercent: 34,
          widthPercent: 18,
          heightPercent: 37,
          zIndex: 2,
          fit: "cover",
          radius: "0.18rem",
          style: { border: "2px solid #111827", background: "#ffffff" },
        },
        {
          id: "photo-caption",
          type: "staticText",
          value: "Official portrait",
          xPercent: 5,
          yPercent: 73,
          widthPercent: 18,
          heightPercent: 4,
          zIndex: 2,
          style: {
            color: "#111827",
            fontSize: 7,
            fontWeight: 800,
            align: "center",
            letterSpacing: "0.1em",
            textTransform: "uppercase",
          },
        },
        {
          id: "name-label",
          type: "staticText",
          value: "Name",
          xPercent: 28,
          yPercent: 32,
          widthPercent: 48,
          heightPercent: 4,
          zIndex: 2,
          style: { color: "#4b5563", fontSize: 8, fontWeight: 800, letterSpacing: "0.12em", textTransform: "uppercase" },
        },
        {
          id: "name-value",
          type: "text",
          sourceKey: "fullName",
          xPercent: 28,
          yPercent: 36,
          widthPercent: 48,
          heightPercent: 8,
          zIndex: 2,
          style: { color: "#111827", fontSize: 15, fontWeight: 900, lineHeight: 1.05, textTransform: "uppercase" },
        },
        {
          id: "birth-label",
          type: "staticText",
          value: "Date of Birth",
          xPercent: 28,
          yPercent: 47,
          widthPercent: 22,
          heightPercent: 4,
          zIndex: 2,
          style: { color: "#4b5563", fontSize: 8, fontWeight: 800, letterSpacing: "0.12em", textTransform: "uppercase" },
        },
        {
          id: "birth-value",
          type: "text",
          sourceKey: "birthDate",
          xPercent: 28,
          yPercent: 51,
          widthPercent: 22,
          heightPercent: 6,
          zIndex: 2,
          style: { color: "#111827", fontSize: 11, fontWeight: 800, textTransform: "uppercase" },
        },
        {
          id: "position-label",
          type: "staticText",
          value: "Position",
          xPercent: 55,
          yPercent: 47,
          widthPercent: 25,
          heightPercent: 4,
          zIndex: 2,
          style: { color: "#4b5563", fontSize: 8, fontWeight: 800, letterSpacing: "0.12em", textTransform: "uppercase" },
        },
        {
          id: "position-value",
          type: "text",
          sourceKey: "displayPosition",
          xPercent: 55,
          yPercent: 51,
          widthPercent: 25,
          heightPercent: 7,
          zIndex: 2,
          style: { color: "#111827", fontSize: 11, fontWeight: 800, lineHeight: 1.1, textTransform: "uppercase" },
        },
        {
          id: "address-label",
          type: "staticText",
          value: "Address",
          xPercent: 28,
          yPercent: 61,
          widthPercent: 52,
          heightPercent: 4,
          zIndex: 2,
          style: { color: "#4b5563", fontSize: 8, fontWeight: 800, letterSpacing: "0.12em", textTransform: "uppercase" },
        },
        {
          id: "address-value",
          type: "text",
          sourceKey: "address",
          xPercent: 28,
          yPercent: 65,
          widthPercent: 52,
          heightPercent: 9,
          zIndex: 2,
          style: { color: "#111827", fontSize: 10, fontWeight: 800, lineHeight: 1.12, textTransform: "uppercase" },
        },
        {
          id: "id-label",
          type: "staticText",
          value: "ID No.",
          xPercent: 28,
          yPercent: 78,
          widthPercent: 24,
          heightPercent: 4,
          zIndex: 2,
          style: { color: "#4b5563", fontSize: 8, fontWeight: 800, letterSpacing: "0.12em", textTransform: "uppercase" },
        },
        {
          id: "id-value",
          type: "text",
          sourceKey: "documentId",
          xPercent: 28,
          yPercent: 82,
          widthPercent: 24,
          heightPercent: 5,
          zIndex: 2,
          style: { color: "#111827", fontSize: 10, fontWeight: 900, textTransform: "uppercase" },
        },
        {
          id: "term-label",
          type: "staticText",
          value: "Term of Service",
          xPercent: 55,
          yPercent: 78,
          widthPercent: 25,
          heightPercent: 4,
          zIndex: 2,
          style: { color: "#4b5563", fontSize: 8, fontWeight: 800, letterSpacing: "0.12em", textTransform: "uppercase" },
        },
        {
          id: "term-value",
          type: "text",
          sourceKey: "serviceTerm",
          xPercent: 55,
          yPercent: 82,
          widthPercent: 25,
          heightPercent: 5,
          zIndex: 2,
          style: { color: "#111827", fontSize: 10, fontWeight: 900, textTransform: "uppercase" },
        },
        {
          id: "signature-label",
          type: "staticText",
          value: "Official signature",
          xPercent: 82,
          yPercent: 68,
          widthPercent: 13,
          heightPercent: 4,
          zIndex: 2,
          style: { color: "#111827", fontSize: 7, fontWeight: 800, align: "center", letterSpacing: "0.08em", textTransform: "uppercase" },
        },
        {
          id: "signature-line",
          type: "shape",
          xPercent: 82,
          yPercent: 75,
          widthPercent: 13,
          heightPercent: 0.5,
          zIndex: 2,
          style: { background: "#111827" },
        },
        {
          id: "front-footer-line",
          type: "shape",
          xPercent: 0,
          yPercent: 89,
          widthPercent: 100,
          heightPercent: 1.1,
          zIndex: 1,
          style: { background: "#8c0909" },
        },
        {
          id: "sktech-logo",
          type: "image",
          sourceKey: "sktechLogoUrl",
          xPercent: 5,
          yPercent: 91,
          widthPercent: 12,
          heightPercent: 6,
          zIndex: 2,
          fit: "contain",
        },
        {
          id: "municipality-status",
          type: "text",
          sourceKey: "municipalityStatus",
          xPercent: 38,
          yPercent: 92,
          widthPercent: 24,
          heightPercent: 4,
          zIndex: 2,
          style: { color: "#111827", fontSize: 8, fontWeight: 900, align: "center", letterSpacing: "0.08em", textTransform: "uppercase" },
        },
        {
          id: "front-watermark",
          type: "text",
          sourceKey: "watermark",
          xPercent: 8,
          yPercent: 97,
          widthPercent: 84,
          heightPercent: 3,
          zIndex: 2,
          style: { color: "#4b5563", fontSize: 6, fontWeight: 900, align: "center", letterSpacing: "0.04em", textTransform: "uppercase" },
        },
      ],
    },
    back: {
      fields: [
        {
          id: "back-background",
          type: "shape",
          xPercent: 0,
          yPercent: 0,
          widthPercent: 100,
          heightPercent: 100,
          zIndex: 0,
          style: { background: "#071b3d" },
        },
        {
          id: "gold-left",
          type: "shape",
          xPercent: 0,
          yPercent: 0,
          widthPercent: 1.4,
          heightPercent: 100,
          zIndex: 1,
          style: { background: "#d4ad43" },
        },
        {
          id: "blue-left",
          type: "shape",
          xPercent: 3.2,
          yPercent: 0,
          widthPercent: 1,
          heightPercent: 100,
          zIndex: 1,
          style: { background: "#458ebe" },
        },
        {
          id: "qr-box",
          type: "qr",
          sourceKey: "qrValue",
          xPercent: 6,
          yPercent: 28,
          widthPercent: 16,
          heightPercent: 25,
          zIndex: 2,
          style: { background: "#ffffff", border: "4px solid #ffffff" },
        },
        {
          id: "qr-label",
          type: "staticText",
          value: "Scan to verify",
          xPercent: 5,
          yPercent: 56,
          widthPercent: 18,
          heightPercent: 5,
          zIndex: 2,
          style: { color: "#f4d36a", fontSize: 8, fontWeight: 900, align: "center", letterSpacing: "0.16em", textTransform: "uppercase" },
        },
        {
          id: "back-heading-small",
          type: "staticText",
          value: "Official identification record",
          xPercent: 29,
          yPercent: 22,
          widthPercent: 36,
          heightPercent: 4,
          zIndex: 2,
          style: { color: "#f4d36a", fontSize: 8, fontWeight: 800, letterSpacing: "0.16em", textTransform: "uppercase" },
        },
        {
          id: "back-heading",
          type: "text",
          sourceKey: "provinceFederation",
          xPercent: 29,
          yPercent: 27,
          widthPercent: 38,
          heightPercent: 7,
          zIndex: 2,
          style: { color: "#ffffff", fontSize: 16, fontWeight: 900, letterSpacing: "0.08em", textTransform: "uppercase" },
        },
        {
          id: "serial-label",
          type: "staticText",
          value: "Serial / ID No.",
          xPercent: 29,
          yPercent: 40,
          widthPercent: 18,
          heightPercent: 4,
          zIndex: 2,
          style: { color: "#a9bdd4", fontSize: 8, fontWeight: 800, letterSpacing: "0.12em", textTransform: "uppercase" },
        },
        {
          id: "serial-value",
          type: "text",
          sourceKey: "documentId",
          xPercent: 29,
          yPercent: 44,
          widthPercent: 28,
          heightPercent: 5,
          zIndex: 2,
          style: { color: "#ffffff", fontSize: 11, fontWeight: 900, textTransform: "uppercase" },
        },
        {
          id: "birth-back-label",
          type: "staticText",
          value: "Birth Date",
          xPercent: 29,
          yPercent: 54,
          widthPercent: 18,
          heightPercent: 4,
          zIndex: 2,
          style: { color: "#a9bdd4", fontSize: 8, fontWeight: 800, letterSpacing: "0.12em", textTransform: "uppercase" },
        },
        {
          id: "birth-back-value",
          type: "text",
          sourceKey: "birthDate",
          xPercent: 29,
          yPercent: 58,
          widthPercent: 20,
          heightPercent: 5,
          zIndex: 2,
          style: { color: "#ffffff", fontSize: 10, fontWeight: 800, textTransform: "uppercase" },
        },
        {
          id: "elected-label",
          type: "staticText",
          value: "Date Elected",
          xPercent: 52,
          yPercent: 54,
          widthPercent: 18,
          heightPercent: 4,
          zIndex: 2,
          style: { color: "#a9bdd4", fontSize: 8, fontWeight: 800, letterSpacing: "0.12em", textTransform: "uppercase" },
        },
        {
          id: "elected-value",
          type: "text",
          sourceKey: "dateElected",
          xPercent: 52,
          yPercent: 58,
          widthPercent: 20,
          heightPercent: 5,
          zIndex: 2,
          style: { color: "#ffffff", fontSize: 10, fontWeight: 800, textTransform: "uppercase" },
        },
        {
          id: "contact-label",
          type: "staticText",
          value: "Contact",
          xPercent: 29,
          yPercent: 68,
          widthPercent: 18,
          heightPercent: 4,
          zIndex: 2,
          style: { color: "#a9bdd4", fontSize: 8, fontWeight: 800, letterSpacing: "0.12em", textTransform: "uppercase" },
        },
        {
          id: "contact-value",
          type: "text",
          sourceKey: "contactNo",
          xPercent: 29,
          yPercent: 72,
          widthPercent: 20,
          heightPercent: 5,
          zIndex: 2,
          style: { color: "#ffffff", fontSize: 10, fontWeight: 800 },
        },
        {
          id: "email-label",
          type: "staticText",
          value: "Email",
          xPercent: 52,
          yPercent: 68,
          widthPercent: 18,
          heightPercent: 4,
          zIndex: 2,
          style: { color: "#a9bdd4", fontSize: 8, fontWeight: 800, letterSpacing: "0.12em", textTransform: "uppercase" },
        },
        {
          id: "email-value",
          type: "text",
          sourceKey: "email",
          xPercent: 52,
          yPercent: 72,
          widthPercent: 22,
          heightPercent: 5,
          zIndex: 2,
          style: { color: "#ffffff", fontSize: 9, fontWeight: 800 },
        },
        {
          id: "back-logo",
          type: "image",
          sourceKey: "sktechLogoUrl",
          xPercent: 76,
          yPercent: 25,
          widthPercent: 16,
          heightPercent: 9,
          zIndex: 2,
          fit: "contain",
        },
        {
          id: "contact-info",
          type: "text",
          sourceKey: "contactInfo",
          xPercent: 75,
          yPercent: 40,
          widthPercent: 20,
          heightPercent: 27,
          zIndex: 2,
          style: { color: "#dbeafe", fontSize: 9, fontWeight: 400, lineHeight: 1.35 },
        },
        {
          id: "website",
          type: "text",
          sourceKey: "websiteUrl",
          xPercent: 75,
          yPercent: 70,
          widthPercent: 20,
          heightPercent: 4,
          zIndex: 2,
          style: { color: "#f4d36a", fontSize: 8, fontWeight: 800, letterSpacing: "0.08em", textTransform: "uppercase" },
        },
        {
          id: "issued",
          type: "text",
          sourceKey: "issuedLabel",
          xPercent: 75,
          yPercent: 75,
          widthPercent: 20,
          heightPercent: 4,
          zIndex: 2,
          style: { color: "#ffffff", fontSize: 7, fontWeight: 500, textTransform: "uppercase", opacity: 0.6 },
        },
        {
          id: "back-watermark",
          type: "text",
          sourceKey: "watermark",
          xPercent: 6,
          yPercent: 93,
          widthPercent: 88,
          heightPercent: 4,
          zIndex: 2,
          style: { color: "#ffffff", fontSize: 7, fontWeight: 900, align: "center", letterSpacing: "0.08em", textTransform: "uppercase", opacity: 0.55 },
        },
      ],
    },
  },
};
