export type IdTemplateSide = "front" | "back";

export type IdTemplateFieldType = "staticText" | "text" | "image" | "qr" | "shape";

export type IdTemplateTextStyle = {
  fontSize?: number;
  fontWeight?: number | string;
  color?: string;
  align?: "left" | "center" | "right";
  lineHeight?: number;
  letterSpacing?: string;
  textTransform?: "none" | "uppercase" | "lowercase" | "capitalize";
  fontStyle?: "normal" | "italic";
};

export type IdTemplateField = {
  id: string;
  type: IdTemplateFieldType;
  assetId?: string;
  sourceKey?: string;
  imageUrl?: string;
  value?: string;
  xPercent: number;
  yPercent: number;
  widthPercent: number;
  heightPercent: number;
  zIndex?: number;
  fit?: "cover" | "contain" | "fill";
  radius?: string;
  visible?: boolean;
  style?: IdTemplateTextStyle & {
    background?: string;
    border?: string;
    opacity?: number;
    imageZoom?: number;
    objectPositionX?: number;
    objectPositionY?: number;
  };
};

export type IdTemplate = {
  version: number;
  canvas: {
    width: number;
    height: number;
  };
  sides: Record<IdTemplateSide, { fields: IdTemplateField[] }>;
};

export const DEFAULT_ID_TEMPLATE: IdTemplate = {
  version: 1,
  canvas: {
    width: 856,
    height: 539.8,
  },
  sides: {
    front: {
      fields: [
        {
          id: "front-background",
          type: "shape",
          xPercent: 0,
          yPercent: 0,
          widthPercent: 100,
          heightPercent: 100,
          zIndex: 0,
          style: { background: "#d9d9d9" },
        },
        {
          id: "front-header",
          type: "shape",
          xPercent: 0,
          yPercent: 0,
          widthPercent: 100,
          heightPercent: 19,
          zIndex: 1,
          style: { background: "#071b3d" },
        },
        {
          id: "provincial-seal",
          type: "image",
          sourceKey: "provincialSealUrl",
          xPercent: 3,
          yPercent: 3,
          widthPercent: 9,
          heightPercent: 13,
          zIndex: 2,
          fit: "contain",
        },
        {
          id: "province-name",
          type: "text",
          sourceKey: "province",
          xPercent: 18,
          yPercent: 5,
          widthPercent: 64,
          heightPercent: 6,
          zIndex: 2,
          style: {
            color: "#ffffff",
            fontSize: 18,
            fontWeight: 900,
            align: "center",
            letterSpacing: "0.22em",
            textTransform: "uppercase",
          },
        },
        {
          id: "federation-label",
          type: "staticText",
          value: "Sangguniang Kabataan Provincial Federation",
          xPercent: 22,
          yPercent: 12,
          widthPercent: 56,
          heightPercent: 4,
          zIndex: 2,
          style: {
            color: "#eef4ff",
            fontSize: 8,
            fontWeight: 700,
            align: "center",
            letterSpacing: "0.1em",
            textTransform: "uppercase",
          },
        },
        {
          id: "sk-logo",
          type: "image",
          sourceKey: "skfedLogoUrl",
          xPercent: 87,
          yPercent: 3,
          widthPercent: 10,
          heightPercent: 13,
          zIndex: 2,
          fit: "contain",
        },
        {
          id: "title-band",
          type: "shape",
          xPercent: 0,
          yPercent: 25,
          widthPercent: 100,
          heightPercent: 1.1,
          zIndex: 1,
          style: { background: "#8c0909" },
        },
        {
          id: "card-title",
          type: "staticText",
          value: "Identification Card",
          xPercent: 28,
          yPercent: 21,
          widthPercent: 44,
          heightPercent: 5,
          zIndex: 2,
          style: {
            color: "#111827",
            fontSize: 15,
            fontWeight: 900,
            align: "center",
            letterSpacing: "0.22em",
            textTransform: "uppercase",
          },
        },
        {
          id: "official-photo",
          type: "image",
          sourceKey: "photoUrl",
          xPercent: 5,
          yPercent: 34,
          widthPercent: 18,
          heightPercent: 37,
          zIndex: 2,
          fit: "cover",
          radius: "0.18rem",
          style: { border: "2px solid #111827", background: "#ffffff" },
        },
        {
          id: "photo-caption",
          type: "staticText",
          value: "Official portrait",
          xPercent: 5,
          yPercent: 73,
          widthPercent: 18,
          heightPercent: 4,
          zIndex: 2,
          style: {
            color: "#111827",
            fontSize: 7,
            fontWeight: 800,
            align: "center",
            letterSpacing: "0.1em",
            textTransform: "uppercase",
          },
        },
        {
          id: "name-label",
          type: "staticText",
          value: "Name",
          xPercent: 28,
          yPercent: 32,
          widthPercent: 48,
          heightPercent: 4,
          zIndex: 2,
          style: { color: "#4b5563", fontSize: 8, fontWeight: 800, letterSpacing: "0.12em", textTransform: "uppercase" },
        },
        {
          id: "name-value",
          type: "text",
          sourceKey: "fullName",
          xPercent: 28,
          yPercent: 36,
          widthPercent: 48,
          heightPercent: 8,
          zIndex: 2,
          style: { color: "#111827", fontSize: 15, fontWeight: 900, lineHeight: 1.05, textTransform: "uppercase" },
        },
        {
          id: "birth-label",
          type: "staticText",
          value: "Date of Birth",
          xPercent: 28,
          yPercent: 47,
          widthPercent: 22,
          heightPercent: 4,
          zIndex: 2,
          style: { color: "#4b5563", fontSize: 8, fontWeight: 800, letterSpacing: "0.12em", textTransform: "uppercase" },
        },
        {
          id: "birth-value",
          type: "text",
          sourceKey: "birthDate",
          xPercent: 28,
          yPercent: 51,
          widthPercent: 22,
          heightPercent: 6,
          zIndex: 2,
          style: { color: "#111827", fontSize: 11, fontWeight: 800, textTransform: "uppercase" },
        },
        {
          id: "position-label",
          type: "staticText",
          value: "Position",
          xPercent: 55,
          yPercent: 47,
          widthPercent: 25,
          heightPercent: 4,
          zIndex: 2,
          style: { color: "#4b5563", fontSize: 8, fontWeight: 800, letterSpacing: "0.12em", textTransform: "uppercase" },
        },
        {
          id: "position-value",
          type: "text",
          sourceKey: "displayPosition",
          xPercent: 55,
          yPercent: 51,
          widthPercent: 25,
          heightPercent: 7,
          zIndex: 2,
          style: { color: "#111827", fontSize: 11, fontWeight: 800, lineHeight: 1.1, textTransform: "uppercase" },
        },
        {
          id: "address-label",
          type: "staticText",
          value: "Address",
          xPercent: 28,
          yPercent: 61,
          widthPercent: 52,
          heightPercent: 4,
          zIndex: 2,
          style: { color: "#4b5563", fontSize: 8, fontWeight: 800, letterSpacing: "0.12em", textTransform: "uppercase" },
        },
        {
          id: "address-value",
          type: "text",
          sourceKey: "address",
          xPercent: 28,
          yPercent: 65,
          widthPercent: 52,
          heightPercent: 9,
          zIndex: 2,
          style: { color: "#111827", fontSize: 10, fontWeight: 800, lineHeight: 1.12, textTransform: "uppercase" },
        },
        {
          id: "id-label",
          type: "staticText",
          value: "ID No.",
          xPercent: 28,
          yPercent: 78,
          widthPercent: 24,
          heightPercent: 4,
          zIndex: 2,
          style: { color: "#4b5563", fontSize: 8, fontWeight: 800, letterSpacing: "0.12em", textTransform: "uppercase" },
        },
        {
          id: "id-value",
          type: "text",
          sourceKey: "documentId",
          xPercent: 28,
          yPercent: 82,
          widthPercent: 24,
          heightPercent: 5,
          zIndex: 2,
          style: { color: "#111827", fontSize: 10, fontWeight: 900, textTransform: "uppercase" },
        },
        {
          id: "term-label",
          type: "staticText",
          value: "Term of Service",
          xPercent: 55,
          yPercent: 78,
          widthPercent: 25,
          heightPercent: 4,
          zIndex: 2,
          style: { color: "#4b5563", fontSize: 8, fontWeight: 800, letterSpacing: "0.12em", textTransform: "uppercase" },
        },
        {
          id: "term-value",
          type: "text",
          sourceKey: "serviceTerm",
          xPercent: 55,
          yPercent: 82,
          widthPercent: 25,
          heightPercent: 5,
          zIndex: 2,
          style: { color: "#111827", fontSize: 10, fontWeight: 900, textTransform: "uppercase" },
        },
        {
          id: "signature-label",
          type: "staticText",
          value: "Official signature",
          xPercent: 82,
          yPercent: 68,
          widthPercent: 13,
          heightPercent: 4,
          zIndex: 2,
          style: { color: "#111827", fontSize: 7, fontWeight: 800, align: "center", letterSpacing: "0.08em", textTransform: "uppercase" },
        },
        {
          id: "signature-line",
          type: "shape",
          xPercent: 82,
          yPercent: 75,
          widthPercent: 13,
          heightPercent: 0.5,
          zIndex: 2,
          style: { background: "#111827" },
        },
        {
          id: "front-footer-line",
          type: "shape",
          xPercent: 0,
          yPercent: 89,
          widthPercent: 100,
          heightPercent: 1.1,
          zIndex: 1,
          style: { background: "#8c0909" },
        },
        {
          id: "sktech-logo",
          type: "image",
          sourceKey: "sktechLogoUrl",
          xPercent: 5,
          yPercent: 91,
          widthPercent: 12,
          heightPercent: 6,
          zIndex: 2,
          fit: "contain",
        },
        {
          id: "municipality-status",
          type: "text",
          sourceKey: "municipalityStatus",
          xPercent: 38,
          yPercent: 92,
          widthPercent: 24,
          heightPercent: 4,
          zIndex: 2,
          style: { color: "#111827", fontSize: 8, fontWeight: 900, align: "center", letterSpacing: "0.08em", textTransform: "uppercase" },
        },
        {
          id: "front-watermark",
          type: "text",
          sourceKey: "watermark",
          xPercent: 8,
          yPercent: 97,
          widthPercent: 84,
          heightPercent: 3,
          zIndex: 2,
          style: { color: "#4b5563", fontSize: 6, fontWeight: 900, align: "center", letterSpacing: "0.04em", textTransform: "uppercase" },
        },
      ],
    },
    back: {
      fields: [
        {
          id: "back-background",
          type: "shape",
          xPercent: 0,
          yPercent: 0,
          widthPercent: 100,
          heightPercent: 100,
          zIndex: 0,
          style: { background: "linear-gradient(135deg, #071733 0%, #102f60 55%, #07152e 100%)" },
        },
        {
          id: "gold-left",
          type: "shape",
          xPercent: 0,
          yPercent: 0,
          widthPercent: 1.2,
          heightPercent: 100,
          zIndex: 1,
          style: { background: "#f1c843" },
        },
        {
          id: "blue-left",
          type: "shape",
          xPercent: 0,
          yPercent: 19,
          widthPercent: 100,
          heightPercent: 0.8,
          zIndex: 1,
          style: { background: "linear-gradient(90deg, #cf2638 0% 34%, #f3c72b 34% 50%, #4d9be9 50% 100%)" },
        },
        {
          id: "back-inner-panel",
          type: "shape",
          xPercent: 4,
          yPercent: 23,
          widthPercent: 92,
          heightPercent: 65,
          zIndex: 1,
          radius: "18px",
          style: { background: "rgba(255,255,255,0.045)", border: "1px solid rgba(186,214,255,0.25)" },
        },
        {
          id: "verification-panel",
          type: "shape",
          xPercent: 6,
          yPercent: 27,
          widthPercent: 25,
          heightPercent: 55,
          zIndex: 1,
          radius: "15px",
          style: { background: "#f7faff", border: "2px solid #e8c763" },
        },
        {
          id: "back-brand",
          type: "staticText",
          value: "SKTECH  /  OFFICIAL CREDENTIAL",
          xPercent: 6,
          yPercent: 6,
          widthPercent: 62,
          heightPercent: 5,
          zIndex: 2,
          style: { color: "#ffffff", fontSize: 15, fontWeight: 900, letterSpacing: "0.16em" },
        },
        {
          id: "back-brand-subtitle",
          type: "staticText",
          value: "ORIENTAL MINDORO  ·  SK FEDERATION",
          xPercent: 6,
          yPercent: 12,
          widthPercent: 62,
          heightPercent: 4,
          zIndex: 2,
          style: { color: "#bfd8fa", fontSize: 9, fontWeight: 700, letterSpacing: "0.14em" },
        },
        {
          id: "qr-box",
          type: "qr",
          sourceKey: "qrValue",
          xPercent: 8,
          yPercent: 33,
          widthPercent: 21,
          heightPercent: 34,
          zIndex: 2,
          style: { background: "#ffffff", border: "4px solid #ffffff" },
        },
        {
          id: "qr-label",
          type: "staticText",
          value: "Scan to verify",
          xPercent: 7,
          yPercent: 71,
          widthPercent: 23,
          heightPercent: 5,
          zIndex: 2,
          style: { color: "#12315f", fontSize: 9, fontWeight: 900, align: "center", letterSpacing: "0.12em", textTransform: "uppercase" },
        },
        {
          id: "back-heading-small",
          type: "staticText",
          value: "OFFICIAL IDENTIFICATION RECORD",
          xPercent: 35,
          yPercent: 28,
          widthPercent: 55,
          heightPercent: 4,
          zIndex: 2,
          style: { color: "#f4d36a", fontSize: 9, fontWeight: 900, letterSpacing: "0.14em" },
        },
        {
          id: "back-heading",
          type: "text",
          sourceKey: "provinceFederation",
          xPercent: 35,
          yPercent: 34,
          widthPercent: 56,
          heightPercent: 8,
          zIndex: 2,
          style: { color: "#ffffff", fontSize: 17, fontWeight: 900, letterSpacing: "0.05em", textTransform: "uppercase" },
        },
        {
          id: "back-heading-rule",
          type: "shape",
          xPercent: 35,
          yPercent: 44,
          widthPercent: 55,
          heightPercent: 0.35,
          zIndex: 2,
          style: { background: "rgba(214,232,255,0.42)" },
        },
        {
          id: "serial-label",
          type: "staticText",
          value: "Serial / ID No.",
          xPercent: 35,
          yPercent: 49,
          widthPercent: 18,
          heightPercent: 4,
          zIndex: 2,
          style: { color: "#a9bdd4", fontSize: 8, fontWeight: 800, letterSpacing: "0.12em", textTransform: "uppercase" },
        },
        {
          id: "serial-value",
          type: "text",
          sourceKey: "documentId",
          xPercent: 35,
          yPercent: 54,
          widthPercent: 43,
          heightPercent: 6,
          zIndex: 2,
          style: { color: "#ffffff", fontSize: 14, fontWeight: 900, letterSpacing: "0.08em", textTransform: "uppercase" },
        },
        {
          id: "birth-back-label",
          type: "staticText",
          visible: false,
          value: "Birth Date",
          xPercent: 29,
          yPercent: 54,
          widthPercent: 18,
          heightPercent: 4,
          zIndex: 2,
          style: { color: "#a9bdd4", fontSize: 8, fontWeight: 800, letterSpacing: "0.12em", textTransform: "uppercase" },
        },
        {
          id: "birth-back-value",
          type: "text",
          visible: false,
          sourceKey: "birthDate",
          xPercent: 29,
          yPercent: 58,
          widthPercent: 20,
          heightPercent: 5,
          zIndex: 2,
          style: { color: "#ffffff", fontSize: 10, fontWeight: 800, textTransform: "uppercase" },
        },
        {
          id: "elected-label",
          type: "staticText",
          value: "Date Elected",
          xPercent: 79,
          yPercent: 49,
          widthPercent: 18,
          heightPercent: 4,
          zIndex: 2,
          style: { color: "#a9bdd4", fontSize: 8, fontWeight: 800, letterSpacing: "0.12em", textTransform: "uppercase" },
        },
        {
          id: "elected-value",
          type: "text",
          sourceKey: "dateElected",
          xPercent: 79,
          yPercent: 54,
          widthPercent: 15,
          heightPercent: 5,
          zIndex: 2,
          style: { color: "#ffffff", fontSize: 10, fontWeight: 800, textTransform: "uppercase" },
        },
        {
          id: "contact-label",
          type: "staticText",
          visible: false,
          value: "Contact",
          xPercent: 29,
          yPercent: 68,
          widthPercent: 18,
          heightPercent: 4,
          zIndex: 2,
          style: { color: "#a9bdd4", fontSize: 8, fontWeight: 800, letterSpacing: "0.12em", textTransform: "uppercase" },
        },
        {
          id: "contact-value",
          type: "text",
          visible: false,
          sourceKey: "contactNo",
          xPercent: 29,
          yPercent: 72,
          widthPercent: 20,
          heightPercent: 5,
          zIndex: 2,
          style: { color: "#ffffff", fontSize: 10, fontWeight: 800 },
        },
        {
          id: "email-label",
          type: "staticText",
          visible: false,
          value: "Email",
          xPercent: 52,
          yPercent: 68,
          widthPercent: 18,
          heightPercent: 4,
          zIndex: 2,
          style: { color: "#a9bdd4", fontSize: 8, fontWeight: 800, letterSpacing: "0.12em", textTransform: "uppercase" },
        },
        {
          id: "email-value",
          type: "text",
          visible: false,
          sourceKey: "email",
          xPercent: 52,
          yPercent: 72,
          widthPercent: 22,
          heightPercent: 5,
          zIndex: 2,
          style: { color: "#ffffff", fontSize: 9, fontWeight: 800 },
        },
        {
          id: "back-logo",
          type: "image",
          sourceKey: "sktechLogoUrl",
          xPercent: 82,
          yPercent: 1,
          widthPercent: 10,
          heightPercent: 17,
          zIndex: 2,
          fit: "contain",
        },
        {
          id: "contact-info",
          type: "text",
          sourceKey: "contactInfo",
          xPercent: 35,
          yPercent: 64,
          widthPercent: 56,
          heightPercent: 12,
          zIndex: 2,
          style: { color: "#dbeafe", fontSize: 10, fontWeight: 500, lineHeight: 1.25 },
        },
        {
          id: "validation-line",
          type: "shape",
          xPercent: 71,
          yPercent: 79,
          widthPercent: 20,
          heightPercent: 0.3,
          zIndex: 2,
          style: { background: "#f4d36a" },
        },
        {
          id: "validation-label",
          type: "staticText",
          value: "Registry validation",
          xPercent: 70,
          yPercent: 80,
          widthPercent: 22,
          heightPercent: 4,
          zIndex: 2,
          style: { color: "#c9ddfa", fontSize: 8, fontWeight: 800, align: "center", letterSpacing: "0.1em", textTransform: "uppercase" },
        },
        {
          id: "website",
          type: "text",
          sourceKey: "websiteUrl",
          xPercent: 35,
          yPercent: 80,
          widthPercent: 28,
          heightPercent: 4,
          zIndex: 2,
          style: { color: "#f4d36a", fontSize: 8, fontWeight: 800, letterSpacing: "0.08em", textTransform: "uppercase" },
        },
        {
          id: "issued",
          type: "text",
          sourceKey: "issuedLabel",
          xPercent: 35,
          yPercent: 85,
          widthPercent: 30,
          heightPercent: 4,
          zIndex: 2,
          style: { color: "#dbeafe", fontSize: 7, fontWeight: 600, textTransform: "uppercase", opacity: 0.8 },
        },
        {
          id: "back-footer-strip",
          type: "shape",
          xPercent: 0,
          yPercent: 91,
          widthPercent: 100,
          heightPercent: 0.8,
          zIndex: 2,
          style: { background: "linear-gradient(90deg, #cf2638 0% 34%, #f3c72b 34% 50%, #4d9be9 50% 100%)" },
        },
        {
          id: "back-watermark",
          type: "text",
          sourceKey: "watermark",
          xPercent: 6,
          yPercent: 94,
          widthPercent: 88,
          heightPercent: 4,
          zIndex: 2,
          style: { color: "#d8e5f8", fontSize: 9, fontWeight: 900, align: "center", letterSpacing: "0.04em", textTransform: "uppercase" },
        },
      ],
    },
  },
};
