import type { KkAnalyticsPayload } from "@/lib/kk/analytics";
import { kkRangeLabel, kkReportSections } from "@/lib/kk/analytics-export";

export default function KkAnalyticsPrintReport({ data, generatedAt }: { data: KkAnalyticsPayload; generatedAt: string }) {
  const sections = kkReportSections(data);
  return <article className="kk-print-report" aria-label="Printable KK analytics report">
    <header className="kk-print-header">
      <p>SKTECH / Oriental Mindoro SK Federation</p>
      <h1>KK Analytics Report</h1>
      <dl>
        <div><dt>Scope</dt><dd>{data.scopeLabel}</dd></div>
        <div><dt>Date range</dt><dd>{kkRangeLabel(data.period.range)}</dd></div>
        <div><dt>Generated</dt><dd>{generatedAt} PHT</dd></div>
      </dl>
      <p className="kk-print-note">The selected period applies to registrations and certificate issuance. Other figures are current all-time snapshots.</p>
    </header>
    {sections.map((section) => <section key={section.title} className="kk-print-section">
      <h2>{section.title}</h2>
      {section.rows.length ? <table><thead><tr><th scope="col">Metric</th><th scope="col">Count / detail</th></tr></thead><tbody>{section.rows.map(([label, value], index) => <tr key={`${label}-${index}`}><th scope="row">{label}</th><td>{value}</td></tr>)}</tbody></table> : <p>No records in this scope.</p>}
    </section>)}
    <footer>Generated by SKTECH. Aggregate analytics only — no private KK profile records included.</footer>
  </article>;
}
